import re

URLS = [
    # URL
    (
        re.compile(r'pool\.'),
        'URL-POOL'
    ),
    (
        re.compile(r'ha\.pool\.'),
        'URL-HA-POOL'
    ),
    (
        re.compile(r'http://'),
        'URL-PROTOCOL-HTTP'
    ),
    (
        re.compile(r'https://'),
        'URL-PROTOCOL-HTTPS'
    ),
    (
        re.compile(r'ftp://'),
        'URL-PROTOCOL-FTP'
    ),
    (
        re.compile(r'git://'),
        'URL-PROTOCOL-GIT'
    ),
    (
        re.compile(r'\.git'),
        'URL-PROTOCOL-GIT'
    ),
]

PATHS = [
    (
        re.compile(r'var/cache/yum'),
        'PATH-VAR-CACHE-YUM'
    ),
    (
        re.compile(r'var/cache/'),
        'PATH-VAR-CACHE'
    ),
    (
        re.compile(r'var/lib/apt/lists'),
        'PATH-APT-LIST'
    ),
    (
        re.compile(r'/src|src/'),
        'PATH-SRC-DIR'
    ),
    (
        re.compile(r'/usr/src'),
        'PATH-USR-SRC-DIR'
    ),
    (
        re.compile(r'/\.cache'),
        'PATH-DOT-CACHE'
    ),
    (
        re.compile(r'^~'),
        'PATH-NORMAL'
    ),
    (
        re.compile(r'^\.$'),
        'PATH-NORMAL'
    ),
    (
        re.compile(r'^/'),
        'PATH-NORMAL'
    ),
    (
        re.compile(r'^(\.)+/'),
        'PATH-NORMAL'
    ),
    (
        re.compile(
            r'(^([a-z]|[A-Z]):(?=\\(?![\0-\37<>:"/\\|?*])|\/(?![\0-\37<>:"/\\|?*])|$)|^\\(?=[\\\/][^\0-\37<>:"/\\|?*]+)|^(?=(\\|\/)$)|^\.(?=(\\|\/)$)|^\.\.(?=(\\|\/)$)|^(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+)|^\.\.(?=(\\|\/)[^\0-\37<>:"/\\|?*]+))((\\|\/)[^\0-\37<>:"/\\|?*]+|(\\|\/)$)*()$'
        ),
        'PATH-NORMAL'
    ),
    (
        re.compile(
            r'^\/$|(^(?=\/)|^\.|^\.\.)(\/(?=[^/\0])[^/\0]+)*\/?$'
        ),
        'PATH-NORMAL'
    ),
]

FILES = [
    (
        re.compile(r'/\.gem'),
        'FILE-GEM'
    ),
    (
        re.compile(r'\.asc'),
        'FILE-ASC'
    ),
    (
        re.compile(r'\.tar\.gz'),
        'FILE-TAR-GZ'
    ),
    (
        re.compile(r'\.tar'),
        'FILE-TAR'
    ),
    (
        re.compile(r'requirements\.txt'),
        'FILE-PIP-REQUIREMENT.TXT'
    ),
    (
        re.compile(r'\.zip'),
        'FILE-ZIP'
    ),
    (
        re.compile(r'package\.json'),
        'FILE-NPM-PACKAGE.JSON'
    ),
    (
        re.compile(r'yarn\.lock'),
        'FILE-YARN-YARN.LOCK'
    ),
    (
        re.compile(r'\.jar'),
        'FILE-JAVA-JAR'
    ),
    (
        re.compile(r'\.sh'),
        'FILE-SHELL-SCRIPT'
    ),
    (
        re.compile(r'\.crt'),
        'FILE-TLS-CERT'
    ),
    (
        re.compile(r'\.pem'),
        'FILE-TLS-CERT'
    ),
    (
        re.compile(r'\.key'),
        'FILE-KEY'
    ),
    (
        re.compile(r'go\.sum'),
        'FILE-GO-SUM'
    ),
    (
        re.compile(r'go\.mod'),
        'FILE-GO-MOD'
    ),
    (
        re.compile(r'Cargo\.toml'),
        'FILE-Rust-Cargo-TOME'
    ),
    (
        re.compile(r'CMakeLists\.txt'),
        'FILE-CMAKEFILE'
    ),
]
OTHER = [
    (
        re.compile(r'^\*$'),
        'GLOB-STAR'
    ),
    (
        re.compile(r'(t|T)rue'),
        'TRUE'
    ),
    (
        re.compile(r'(f|F)alse'),
        'FALSE'
    ),
    (
        re.compile(r'pip3'),
        'pip'
    ),
]
ABSTRACTIONS = [URLS, FILES, PATHS, OTHER]
ABSTRACTIONS_SINGLE = FILES + URLS + PATHS + OTHER
